#!/usr/bin/bas

#6d

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas/animals_with_pheno/6d

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_1_6d.txt -maf 0 -lmm 1 -o index_1_6d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_2_6d.txt -maf 0 -lmm 1 -o index_2_6d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_3_6d.txt -maf 0 -lmm 1 -o index_3_6d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_4_6d.txt -maf 0 -lmm 1 -o index_4_6d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_5_6d.txt -maf 0 -lmm 1 -o index_5_6d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_6_6d.txt -maf 0 -lmm 1 -o index_6_6d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_7_6d.txt -maf 0 -lmm 1 -o index_7_6d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/mass_6d.txt -maf 0 -lmm 1 -o mass_6d_adjust_norm

#42d

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas/animals_with_pheno/42d

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_1_42d.txt -maf 0 -lmm 1 -o index_1_42d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_2_42d.txt -maf 0 -lmm 1 -o index_2_42d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_3_42d.txt -maf 0 -lmm 1 -o index_3_42d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_4_42d.txt -maf 0 -lmm 1 -o index_4_42d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_5_42d.txt -maf 0 -lmm 1 -o index_5_42d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_6_42d.txt -maf 0 -lmm 1 -o index_6_42d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_7_42d.txt -maf 0 -lmm 1 -o index_7_42d_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/mass_42d.txt -maf 0 -lmm 1 -o mass_42d_adjust_norm

#3m

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas/animals_with_pheno/3m

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_1_3m.txt -maf 0 -lmm 1 -o index_1_3m_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_2_3m.txt -maf 0 -lmm 1 -o index_2_3m_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_3_3m.txt -maf 0 -lmm 1 -o index_3_3m_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_4_3m.txt -maf 0 -lmm 1 -o index_4_3m_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_5_3m.txt -maf 0 -lmm 1 -o index_5_3m_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_6_3m.txt -maf 0 -lmm 1 -o index_6_3m_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/index_7_3m.txt -maf 0 -lmm 1 -o index_7_3m_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/mass_3m.txt -maf 0 -lmm 1 -o mass_3m_adjust_norm
