#!/usr/bin/bas

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/gwas/pool_2

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_1_6d_pool_2.txt -lmm 1 -o index_1_6d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_2_6d_pool_2.txt -lmm 1 -o index_2_6d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_3_6d_pool_2.txt -lmm 1 -o index_3_6d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_4_6d_pool_2.txt -lmm 1 -o index_4_6d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_5_6d_pool_2.txt -lmm 1 -o index_5_6d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_6_6d_pool_2.txt -lmm 1 -o index_6_6d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_7_6d_pool_2.txt -lmm 1 -o index_7_6d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_1_42d_pool_2.txt -lmm 1 -o index_1_42d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_2_42d_pool_2.txt -lmm 1 -o index_2_42d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_3_42d_pool_2.txt -lmm 1 -o index_3_42d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_4_42d_pool_2.txt -lmm 1 -o index_4_42d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_5_42d_pool_2.txt -lmm 1 -o index_5_42d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_6_42d_pool_2.txt -lmm 1 -o index_6_42d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_7_42d_pool_2.txt -lmm 1 -o index_7_42d_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_1_3m_pool_2.txt -lmm 1 -o index_1_3m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_2_3m_pool_2.txt -lmm 1 -o index_2_3m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_3_3m_pool_2.txt -lmm 1 -o index_3_3m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_4_3m_pool_2.txt -lmm 1 -o index_4_3m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_5_3m_pool_2.txt -lmm 1 -o index_5_3m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_6_3m_pool_2.txt -lmm 1 -o index_6_3m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_7_3m_pool_2.txt -lmm 1 -o index_7_3m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_1_6m_pool_2.txt -lmm 1 -o index_1_6m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_2_6m_pool_2.txt -lmm 1 -o index_2_6m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_3_6m_pool_2.txt -lmm 1 -o index_3_6m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_4_6m_pool_2.txt -lmm 1 -o index_4_6m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_5_6m_pool_2.txt -lmm 1 -o index_5_6m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_6_6m_pool_2.txt -lmm 1 -o index_6_6m_pool_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/plink_files/pool_2 -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/results/kinship/pool_2.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pool_2_cov.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2020/data/pheno_data/pheno_qc/index_7_6m_pool_2.txt -lmm 1 -o index_7_6m_pool_2
