#!/usr/bin/bas

# imputed pheno

##6d

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas/animals_with_pheno/imputed_pheno/6d

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_1_6d.txt -maf 0 -lmm 1 -o index_1_6d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_2_6d.txt -maf 0 -lmm 1 -o index_2_6d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_3_6d.txt -maf 0 -lmm 1 -o index_3_6d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_4_6d.txt -maf 0 -lmm 1 -o index_4_6d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_5_6d.txt -maf 0 -lmm 1 -o index_5_6d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_6_6d.txt -maf 0 -lmm 1 -o index_6_6d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_7_6d.txt -maf 0 -lmm 1 -o index_7_6d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/mass_6d.txt -maf 0 -lmm 1 -o mass_6d_imp_adjust_norm

##42d

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas/animals_with_pheno/imputed_pheno/42d

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_1_42d.txt -maf 0 -lmm 1 -o index_1_42d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_2_42d.txt -maf 0 -lmm 1 -o index_2_42d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_3_42d.txt -maf 0 -lmm 1 -o index_3_42d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_4_42d.txt -maf 0 -lmm 1 -o index_4_42d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_5_42d.txt -maf 0 -lmm 1 -o index_5_42d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_6_42d.txt -maf 0 -lmm 1 -o index_6_42d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_7_42d.txt -maf 0 -lmm 1 -o index_7_42d_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/mass_42d.txt -maf 0 -lmm 1 -o mass_42d_imp_adjust_norm

##3m

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas/animals_with_pheno/imputed_pheno/3m

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_1_3m.txt -maf 0 -lmm 1 -o index_1_3m_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_2_3m.txt -maf 0 -lmm 1 -o index_2_3m_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_3_3m.txt -maf 0 -lmm 1 -o index_3_3m_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_4_3m.txt -maf 0 -lmm 1 -o index_4_3m_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_5_3m.txt -maf 0 -lmm 1 -o index_5_3m_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_6_3m.txt -maf 0 -lmm 1 -o index_6_3m_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/index_7_3m.txt -maf 0 -lmm 1 -o index_7_3m_imp_adjust_norm
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/imputed/mass_3m.txt -maf 0 -lmm 1 -o mass_3m_imp_adjust_norm

# pc on imputed pheno

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas/animals_with_pheno/pc_on_imputed_pheno

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_1.txt -maf 0 -lmm 1 -o pc_1
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_2.txt -maf 0 -lmm 1 -o pc_2
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_3.txt -maf 0 -lmm 1 -o pc_3
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_4.txt -maf 0 -lmm 1 -o pc_4
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_5.txt -maf 0 -lmm 1 -o pc_5
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_6.txt -maf 0 -lmm 1 -o pc_6
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_7.txt -maf 0 -lmm 1 -o pc_7
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_8.txt -maf 0 -lmm 1 -o pc_8
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_9.txt -maf 0 -lmm 1 -o pc_9
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_10.txt -maf 0 -lmm 1 -o pc_10
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_11.txt -maf 0 -lmm 1 -o pc_11
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_12.txt -maf 0 -lmm 1 -o pc_12
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_13.txt -maf 0 -lmm 1 -o pc_13
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_14.txt -maf 0 -lmm 1 -o pc_14
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_15.txt -maf 0 -lmm 1 -o pc_15
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_16.txt -maf 0 -lmm 1 -o pc_16
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_17.txt -maf 0 -lmm 1 -o pc_17
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_18.txt -maf 0 -lmm 1 -o pc_18
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_19.txt -maf 0 -lmm 1 -o pc_19
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_20.txt -maf 0 -lmm 1 -o pc_20
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_21.txt -maf 0 -lmm 1 -o pc_21
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_22.txt -maf 0 -lmm 1 -o pc_22
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_23.txt -maf 0 -lmm 1 -o pc_23
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/plink_files/122_animals_with_pheno -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/kinship/122_animals_with_pheno.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/results/gwas_staibility_test/data_for_gwas/cov_122.txt -p /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/2021/data/pheno_data/pheno_qc_122_animals/pc/pc_24.txt -maf 0 -lmm 1 -o pc_24
