#!/usr/bin/bas

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/results/gemma_results/42d

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_1_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_1_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_2_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_2_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_3_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_3_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_4_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_4_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_5_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_5_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_6_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_6_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_7_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_7_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_8_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_8_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_9_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_9_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_10_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_10_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_42d/ped_42d_11_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 42d_11_trait
