#!/usr/bin/bas

cd /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/results/gemma_results/3m

/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_1_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_1_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_2_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_2_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_3_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_3_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_4_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_4_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_5_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_5_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_6_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_6_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_7_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_7_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_8_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_8_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_9_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_9_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_10_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_10_trait
/home/common/projects/ovine_selection/Soft/gemma-0.98.1-linux-static -bfile /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/ped_3m/ped_3m_11_trait_filtered -k /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/plink_files/for_all_samples_filtered.aBN.kinf -c /home/common/projects/ovine_selection/GWAS_on_russian_population_of_ovines/data/covariates.txt -lmm 1 -o 3m_11_trait
